- hosts: nagios_hosts
  become: true
  tasks:
    - name: ensure package cache is up to date
      apt: update_cache=yes cache_valid_time=3600
      tags: install

    - name: install Nagios Version 3
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nagios3
        - nagios3-doc
      tags: install

    - name: Check nagios Users
      stat:
        path: /etc/nagios3/htpasswd.users
      ignore_errors: true
      register: nagios_user_pwfile_exists
      tags: configure

    - name: Create empty password file
      command: touch /etc/nagios3/htpasswd.users
      args:
        creates: /etc/nagios3/htpasswd.users
      when: not nagios_user_pwfile_exists
      tags: configure

    - name: Create nagios admin user
      htpasswd:
        path: /etc/nagios3/htpasswd.users
        name: nagiosadmin
        password: "{{ class_password }}"
        state: present
      ignore_errors: true
      tags: configure

